name: FudRush

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.19.1

      - name: Install Dependencies
        run: |
          cd back-end
          npm install
          cd ../front-end
          npm install

      - name: Run Tests
        run: |
          cd front-end
          npm test